### ISSUE TITLE
cannot compute sizeof(int) on crosscompile

### ISSUE THREAD

**Issue by noangel** [cobbal/python-for-iphone#1]
Using Xcode 4.3.2 under Mac OS X 10.7.4.
Slightly pathced script for new Xcode.
Patch works successfully, as also "native build" does.
But it fails next on cross-compile with error:
"checking size of int... configure: error: cannot compute sizeof (int)
See `config.log' for more details."

**Comment by cobbal** [comment]
I believe this is fixed for now; until a new version of Xcode breaks everything of course.
